language: python
python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install

script:
  - cd gtfs_geo
  - wget https://static.data.gouv.fr/resources/agglobus/20200924-091339/200924-agglobus.zip --no-verbose --output-document=gtfs.zip 2>&1
  - python cli.py gtfs.zip
